language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install coverage
  - pip install coveralls
  - pip install pytest-cov

script:
  - python -m pytest --verbose --cov=./ tests
  - coveralls
